### ISSUE TITLE
Correcting and making tests for Java codes

### ISSUE THREAD

**Issue by aniketsharma00411** [aniketsharma00411/algorithmsUse#122]
There are many Java algorithms which do not run and some which don't have proper comments to explain the code. Is someone interested in correcting those and making proper unit tests for them?

**Comment by MahmoudMabrok** [comment]
FIRST U SHOULD ASK ORIGINAL DEVELOPER TO FIX HIS CODE OR REMOVE IT FROM REPO

**Comment by MahmoudMabrok** [comment]
after that i can do Unit tests for it.

**Comment by aniketsharma00411** [comment]
> FIRST U SHOULD ASK ORIGINAL DEVELOPER TO FIX HIS CODE OR REMOVE IT FROM REPO

Are the codes that bad you want them removed?

**Comment by MahmoudMabrok** [comment]
> > FIRST U SHOULD ASK ORIGINAL DEVELOPER TO FIX HIS CODE OR REMOVE IT FROM REPO
> 
> Are the codes that bad you want them removed?

it should be deleted till owner fix it as he only aand most one who know codes and its function 
i think it will lose of time.

we should seek to good quality code

**Comment by aniketsharma00411** [comment]
Ok. Will you list the codes you think should be removed?

I will create a new branch to store them and remove them from master branch.

**Comment by MahmoudMabrok** [comment]
i have faced some of them 
we can make issue and list in it files we find

**Comment by aniketsharma00411** [comment]
Just give me a list of file names and i will remove those. 
Or you can remove them too if you want. As you see fit.
