### ISSUE TITLE
Arrange code in proper directories

### ISSUE THREAD

**Issue by ManasUniyal** [aniketsharma00411/algorithmsUse#145]
- There is no tag for dynamic programming and questions like LCS are lying in miscellaneous category. It is good time to arrange the code in proper directories other wise it won't take long until it gets out of hand

- If you don't mind, I can do it for you and also add codes for matrix exponentiation, range sum using segment trees, Djikstra algorithm, Minimum spanning tree algorithms.

**Comment by aniketsharma00411** [comment]
Ok

I will assign it to you.
