### ISSUE TITLE
Quick Select algorithm in C++

### ISSUE THREAD

**Issue by chirayu-joshi** [aniketsharma00411/algorithmsUse#151]
I would like to add an algorithm to find K-th smallest element in an array. It can be found using various techniques, but quick select is efficient. 

Can I send pull request to add this algorithm? I have read CONTRIBUTING.md file.

Thank you.

**Comment by aniketsharma00411** [comment]
Ok

**Comment by chirayu-joshi** [comment]
I have successfully added the algorithm and tested corner cases. I have also sent pull request. Please consider to review it, and if any changes are required, than please inform me. 

I am closing this issue, but if needed, you can reopen it.
