### ISSUE TITLE
Tree Algorithms in C++

### ISSUE THREAD

**Issue by chirayu-joshi** [aniketsharma00411/algorithmsUse#152]
## I wish to add multiple algorithms of Tree data structure in C++ language like:
- balanced_binary_tree_check
- binary_tree_to_doubly_linkedlist
- binary_tree_from_inorder_preorder

I have read CONTRIBUTING.md file. Can I send pull request regarding addition of these algorithms?

**Comment by aniketsharma00411** [comment]
Ok send the PR.

**Comment by chirayu-joshi** [comment]
I have added these algorithms and tested it. I have sent PR. Please review it and tell me if any changes are needed. 

Thank you.
