### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by aniketsharma00411** [aniketsharma00411/algorithmsUse#39]
Update the README.md file with all the algorithms which are currently present.

**Comment by aayushwadhwa1** [comment]
Hey, can I take up this?

**Comment by simarpreetsingh-019** [comment]
@aniketsharma00411 I want to work on this issue for adding all the algo names present, along with their links in the readme.

**Comment by Kapersky1337** [comment]
I will add and update the README as needed. Please let me also work on this, thank you.

**Comment by aniketsharma00411** [comment]
I don't want to disappoint anyone. So, I will distribute the task.
@simarpreetsingh-019 Will you edit the main README.md?
@aayushwadhwa1 You can edit the README.md of C++, Dart and JavaScript.
@Kapersky1337 You can update the Java and Python README.md

**Comment by aniketsharma00411** [comment]
Hope everyone is fine with it. :)

**Comment by aayushwadhwa1** [comment]
I have created a pull request, can you please check

**Comment by simarpreetsingh-019** [comment]
There is a great list of projects in CPP folder, which will take some time. will be making Pr asap.

it will be a great help if other contributor's pr could be merged first so that it could be easy to track and get names of all sorting algos at one place in their specific folder so that it could bit easy to get and link names and files.

**Comment by aayushwadhwa1** [comment]
do we need to add links? it is not mentioned in the description

**Comment by simarpreetsingh-019** [comment]
> do we need to add links? it is not mentioned in the description

@aayushwadhwa1 no bro you don't need to add links, that task is assigned to me.

**Comment by aniketsharma00411** [comment]
@simarpreetsingh-019 Now you can work on the main README. C++ README I will update later. Till then you can reference others.

**Comment by Nihal-Ahamed-MS** [comment]
Hi @aniketsharma00411, Can you assign me on this.

**Comment by aniketsharma00411** [comment]
> Hi @aniketsharma00411, Can you assign me on this.

Sorry, but the issue is resolved.
